The data is stored in H5AD files which are types of files that store annotated single-cell gene expression data,
and other metadata such as cell annotations, quality control metrics, and feature annotations


In [18]:
import anndata
import numpy as np

In [19]:
# load the data H5AD file
# data is a H5AD file object and contains the gene expression matrix (data.X), cell metadata (data.obs), and gene metadata (data.var)
data = anndata.read_h5ad('/home/data/raw/coin-seq/dixit/DixitRegev2016.h5ad') #this is the path to the data, might vary

In [21]:
# working with the count matrix (data.X)

X = data.X # Accessing the gene expression matrix. data is an anndata object, and X is a sparse matrix representing expression data

print(X.format)

print(data) #the attributes printed after obs: refer to information about each cell, the information printed after var: contains information about each gene
print('number of genes: ', data.n_vars) # columns
print('number of cells: ', data.n_obs) # rows

print('(a, b) means gene index a is expressed in cell index b')
subset = X[:10, :10] #view first 20 cells and genes, this is normalized expression data 
print(subset) #because subset is a sparse matrix a lot of the values in the matrix will be 0, only entries not zero are stored in memory, and this prints out that info
print(subset.dtype)


print('\nthis is what the matrix looks like:')
print(subset.todense()) #this is here for a visual of what the matrix actually looks like, the 0s mean there is no sufficent gene expression in the cell


csc
AnnData object with n_obs × n_vars = 51898 × 23529
    obs: 'perturbation', 'grna_lenient', 'target', 'moi', 'cell_line', 'celltype', 'perturbation_type', 'cancer', 'disease', 'guide_id', 'ncounts', 'ngenes', 'percent_mito', 'percent_ribo', 'nperts'
    var: 'gene_id', 'mt', 'ribo', 'ncounts', 'ncells'
number of genes:  23529
number of cells:  51898
(a, b) means gene index a is expressed in cell index b
  (5, 5)	1.0
float32

this is what the matrix looks like:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# working with the cell metadata (data.obs)
cells = data.obs # each row represents a different cell, and the columns represent metadata associated with that cell
print(cells)

In [ ]:


cellsFound = []
controlCells = []
cells = data.obs
count = 0
numCells = 0
control = 0
cell_names = data.obs_names

# this is used to make a list of all cells that have a specified perturbation, and a list of "control cells"
while count < 51898:
    if cells.perturbation[count] == 'p-sgEGR1-2':
        cellsFound.append(cell_names[count])
        numCells = numCells + 1

    if cells.perturbation[count] == 'control':
        controlCells.append(cell_names[count])
        control = control + 1

    count = count + 1


print(numCells, " cells were found with the specified perturbation")
print(cellsFound)
print(control, " control cells were found")
print(controlCells)


element = "AAACCGTGAGCATC_ph14d_B5"
if element in cellsFound and element in controlCells:
    print(f"{element} is present in both lists.")


def is_sublist(lst, sublst):
    lst.sort()
    sublst.sort()
    i = 0
    for j in range(len(sublst)):
        while i < len(lst) and lst[i] < sublst[j]:
            i += 1
        if i >= len(lst) or lst[i] != sublst[j]:
            print(sublst[j])
            return False
    return True



#lst = [1, 2, 3, 4, 5, 6, 7]
#sublst = [4, 3, 5]

#print(is_sublist(controlCells, cellsFound))


In [ ]:
#and cells.perturbation[counter] == 'control'
#if 'p_sgEGR1_2' in cells.guide_id[counter]:
#ACCGCGGATCGTAG_ph14d_B5

numControl = 0
numPerturbation = 0

"""counter = 0
while counter < 51898:
    if 'AAGCGACTCTGACA_ph14d_B5' in cell_names[counter]:
        print('idenifier: ', cell_names[counter])
        print('perturbation: ' + cells.perturbation[counter])
        print('grna_lenient: ' + cells.grna_lenient[counter])
        print('target: ' , cells.target[counter])
        print('moi: ' + cells.moi[counter])
        print('cell_line: ' + cells.cell_line[counter])
        print('cell type: ' + cells.celltype[counter])
        print('perturbation_type: ' + cells.perturbation_type[counter])
        print('cancer:  ' , cells.cancer[counter])
        print('disease: ' + cells.disease[counter])
        print('guide_id: ' + cells.guide_id[counter])
        print('ncounts: ' , cells.ncounts[counter])
        print('ngenes: ' , cells.ngenes[counter])
        print('percent_mito: ' + cells.perturbation_type[counter])
        print('percent_ribo: ' ,cells.percent_ribo[counter])
        print('nperts: ' , cells.nperts [counter])
        print("\n")
        numControl = numControl + 1

    counter = counter + 1"""
         
counter = 0
while counter < 51898:
    if 'control' in cells.perturbation[counter]:
        print('idenifier: ', cell_names[counter])
        print('perturbation: ' + cells.perturbation[counter])
        print('grna_lenient: ' , cells.grna_lenient[counter])
        print('target: ' , cells.target[counter])
        print('moi: ' + cells.moi[counter])
        print('cell_line: ' + cells.cell_line[counter])
        print('cell type: ' + cells.celltype[counter])
        print('perturbation_type: ' + cells.perturbation_type[counter])
        print('cancer:  ' , cells.cancer[counter])
        print('disease: ' + cells.disease[counter])
        print('guide_id: ' + cells.guide_id[counter])
        print('ncounts: ' , cells.ncounts[counter])
        print('ngenes: ' , cells.ngenes[counter])
        print('percent_mito: ' + cells.perturbation_type[counter])
        print('percent_ribo: ' ,cells.percent_ribo[counter])
        print('nperts: ' , cells.nperts [counter])
        print("\n")

        numPerturbation = numPerturbation + 1
        
    counter = counter + 1


print(numControl)
print(numPerturbation)

In [ ]:
counter = 0
while counter < 51898:
    print('idenifier: ', cell_names[counter])
    counter = counter + 1

In [ ]:
#get all observations for a specified cell, i.e. 0 and 1s for gene expression 
obs_name = 'AAACATACAAGGTA_ph14d_B5'
obs_index = data.obs_names.tolist().index(obs_name)
cell_expression = data.X[obs_index, :].todense()
cell_expression = np.array(cell_expression).flatten()
print(cell_expression[:500])

In [ ]:
#make a sub matrix of the expression matrix only for control cells
subset_obs_names = controlCells #list of observation names to subset
subset_X = data.X[data.obs_names.isin(subset_obs_names)] #subset the .X matrix to only include the desired rows
subset_adata = anndata.AnnData(subset_X) #creating a new anndata object with the subsetted expression matrix
subset_adata.obs_names = subset_obs_names

newX = subset_adata.X
print('number of genes: ', subset_adata.n_vars) # columns
print('number of cells: ', subset_adata.n_obs) # rows
print(newX.todense())

In [ ]:
# working with the gene metadata (data.var)
genes = data.var
print(genes) # each row represents a different gene, and the columns represent metadata associated with that gene

In [ ]:
# dataset annotations
info = data.uns
print(info) # the only overload key is neighbors suggesting the data was processed using neighborhood based analysis (clustering or dimensionality reduction)